/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : BLUE.h
**     Project     : PersonalCloud
**     Processor   : MK64FN1M0VLQ12
**     Component   : LED
**     Version     : Component 01.062, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-02-12, 14:36, # CodeGen: 1
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : BLUE
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**            High Value means ON                          : no
**          Shell                                          : Disabled
**     Contents    :
**         Init       - void BLUE_Init(void);
**         Deinit     - void BLUE_Deinit(void);
**         On         - void BLUE_On(void);
**         Off        - void BLUE_Off(void);
**         Neg        - void BLUE_Neg(void);
**         Get        - byte BLUE_Get(void);
**         Put        - void BLUE_Put(byte val);
**         SetRatio16 - void BLUE_SetRatio16(word ratio);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file BLUE.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup BLUE_module BLUE module documentation
**  @{
*/         

#ifndef __BLUE_H
#define __BLUE_H

/* MODULE BLUE. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin3.h"

#include "Cpu.h"

#define BLUE_ClrVal()    LEDpin3_ClrVal() /* put the pin on low level */
#define BLUE_SetVal()    LEDpin3_SetVal() /* put the pin on high level */
#define BLUE_SetInput()  LEDpin3_SetInput() /* use the pin as input pin */
#define BLUE_SetOutput() LEDpin3_SetOutput() /* use the pin as output pin */

#define BLUE_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define BLUE_On() LEDpin3_ClrVal()
/*
** ===================================================================
**     Method      :  BLUE_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define BLUE_Off() LEDpin3_SetVal()
/*
** ===================================================================
**     Method      :  BLUE_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define BLUE_Neg() LEDpin3_NegVal()
/*
** ===================================================================
**     Method      :  BLUE_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define BLUE_Get() (!(LEDpin3_GetVal()))
/*
** ===================================================================
**     Method      :  BLUE_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

#define BLUE_Init() BLUE_Off()
/*
** ===================================================================
**     Method      :  BLUE_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define BLUE_Put(val)  ((val) ? BLUE_On() : BLUE_Off())
/*
** ===================================================================
**     Method      :  BLUE_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void BLUE_Deinit(void);
/*
** ===================================================================
**     Method      :  BLUE_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void BLUE_SetRatio16(word ratio);
/*
** ===================================================================
**     Method      :  BLUE_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END BLUE. */

#endif
/* ifndef __BLUE_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
