/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : GREEN.h
**     Project     : PersonalCloud
**     Processor   : MK64FN1M0VLQ12
**     Component   : LED
**     Version     : Component 01.062, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-02-12, 14:36, # CodeGen: 1
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : GREEN
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**            High Value means ON                          : no
**          Shell                                          : Disabled
**     Contents    :
**         Init       - void GREEN_Init(void);
**         Deinit     - void GREEN_Deinit(void);
**         On         - void GREEN_On(void);
**         Off        - void GREEN_Off(void);
**         Neg        - void GREEN_Neg(void);
**         Get        - byte GREEN_Get(void);
**         Put        - void GREEN_Put(byte val);
**         SetRatio16 - void GREEN_SetRatio16(word ratio);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file GREEN.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup GREEN_module GREEN module documentation
**  @{
*/         

#ifndef __GREEN_H
#define __GREEN_H

/* MODULE GREEN. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin2.h"

#include "Cpu.h"

#define GREEN_ClrVal()    LEDpin2_ClrVal() /* put the pin on low level */
#define GREEN_SetVal()    LEDpin2_SetVal() /* put the pin on high level */
#define GREEN_SetInput()  LEDpin2_SetInput() /* use the pin as input pin */
#define GREEN_SetOutput() LEDpin2_SetOutput() /* use the pin as output pin */

#define GREEN_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define GREEN_On() LEDpin2_ClrVal()
/*
** ===================================================================
**     Method      :  GREEN_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define GREEN_Off() LEDpin2_SetVal()
/*
** ===================================================================
**     Method      :  GREEN_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define GREEN_Neg() LEDpin2_NegVal()
/*
** ===================================================================
**     Method      :  GREEN_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define GREEN_Get() (!(LEDpin2_GetVal()))
/*
** ===================================================================
**     Method      :  GREEN_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

#define GREEN_Init() GREEN_Off()
/*
** ===================================================================
**     Method      :  GREEN_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define GREEN_Put(val)  ((val) ? GREEN_On() : GREEN_Off())
/*
** ===================================================================
**     Method      :  GREEN_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void GREEN_Deinit(void);
/*
** ===================================================================
**     Method      :  GREEN_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void GREEN_SetRatio16(word ratio);
/*
** ===================================================================
**     Method      :  GREEN_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END GREEN. */

#endif
/* ifndef __GREEN_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
